name: DocBox

on:
  push:
    branches:
      - master
      - main

env:
  MODULE_ID: pstrong
  VERSION: 

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Setup CommandBox CLI
        uses: Ortus-Solutions/setup-commandbox@main

      - run: box install commandbox-docbox
      
      - name: Setup env.VERSION
        run: echo "VERSION=`box package version`" >> $GITHUB_ENV
        
      - run: echo ${{ env.VERSION }}
      
      - name: Generate Docs
        run: box run-script build:docs
      
      - name: Commit Docs to Repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "📖 DOC: Auto-generate API docs"

      # - name: Upload API Docs to S3
      #   uses: jakejarvis/s3-sync-action@master
      #   with:
      #     args: --acl public-read
      #   env:
      #     AWS_S3_BUCKET: "apidocs.ortussolutions.com"
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}
      #     SOURCE_DIR: "docs"
      #     DEST_DIR: "coldbox-modules/${{ env.MODULE_ID }}/${{ env.VERSION }}"